/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiMbazaRouteImport } from './routes/api/mbaza'
import { Route as ApiIremboSearchRouteImport } from './routes/api/irembo/search'
import { Route as ApiIremboLiveSearchRouteImport } from './routes/api/irembo/live/search'
import { Route as ApiIremboLiveServiceRouteImport } from './routes/api/irembo/live/service'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMbazaRoute = ApiMbazaRouteImport.update({
  id: '/api/mbaza',
  path: '/api/mbaza',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIremboSearchRoute = ApiIremboSearchRouteImport.update({
  id: '/api/irembo/search',
  path: '/api/irembo/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIremboLiveSearchRoute = ApiIremboLiveSearchRouteImport.update({
  id: '/api/irembo/live/search',
  path: '/api/irembo/live/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIremboLiveServiceRoute = ApiIremboLiveServiceRouteImport.update({
  id: '/api/irembo/live/service',
  path: '/api/irembo/live/service',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/mbaza': typeof ApiMbazaRoute
  '/api/irembo/search': typeof ApiIremboSearchRoute
  '/api/irembo/live/search': typeof ApiIremboLiveSearchRoute
  '/api/irembo/live/service': typeof ApiIremboLiveServiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/mbaza': typeof ApiMbazaRoute
  '/api/irembo/search': typeof ApiIremboSearchRoute
  '/api/irembo/live/search': typeof ApiIremboLiveSearchRoute
  '/api/irembo/live/service': typeof ApiIremboLiveServiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/mbaza': typeof ApiMbazaRoute
  '/api/irembo/search': typeof ApiIremboSearchRoute
  '/api/irembo/live/search': typeof ApiIremboLiveSearchRoute
  '/api/irembo/live/service': typeof ApiIremboLiveServiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/mbaza'
    | '/api/irembo/search'
    | '/api/irembo/live/search'
    | '/api/irembo/live/service'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/mbaza'
    | '/api/irembo/search'
    | '/api/irembo/live/search'
    | '/api/irembo/live/service'
  id:
    | '__root__'
    | '/'
    | '/api/mbaza'
    | '/api/irembo/search'
    | '/api/irembo/live/search'
    | '/api/irembo/live/service'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiMbazaRoute: typeof ApiMbazaRoute
  ApiIremboSearchRoute: typeof ApiIremboSearchRoute
  ApiIremboLiveSearchRoute: typeof ApiIremboLiveSearchRoute
  ApiIremboLiveServiceRoute: typeof ApiIremboLiveServiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mbaza': {
      id: '/api/mbaza'
      path: '/api/mbaza'
      fullPath: '/api/mbaza'
      preLoaderRoute: typeof ApiMbazaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/irembo/search': {
      id: '/api/irembo/search'
      path: '/api/irembo/search'
      fullPath: '/api/irembo/search'
      preLoaderRoute: typeof ApiIremboSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/irembo/live/search': {
      id: '/api/irembo/live/search'
      path: '/api/irembo/live/search'
      fullPath: '/api/irembo/live/search'
      preLoaderRoute: typeof ApiIremboLiveSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/irembo/live/service': {
      id: '/api/irembo/live/service'
      path: '/api/irembo/live/service'
      fullPath: '/api/irembo/live/service'
      preLoaderRoute: typeof ApiIremboLiveServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiMbazaRoute: ApiMbazaRoute,
  ApiIremboSearchRoute: ApiIremboSearchRoute,
  ApiIremboLiveSearchRoute: ApiIremboLiveSearchRoute,
  ApiIremboLiveServiceRoute: ApiIremboLiveServiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
